{
 "title": "Demo Cluster Dashboard",
 "tags": [ "demo" ],
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[5m]))",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}