apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    app: grafana
data:
  sample-dashboard.json: |
    {
      "id": null,
      "uid": "demo1",
      "title": "Demo Cluster Dashboard",
      "tags": ["demo"],
      "timezone": "browser",
      "schemaVersion": 36,
      "version": 1,
      "refresh": "30s",
      "panels": [
        {
          "type": "graph",
          "title": "CPU Usage",
          "targets": [
            {
              "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m]))",
              "legendFormat": "CPU"
            }
          ],
          "datasource": "Prometheus",
          "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 }
        },
        {
          "type": "graph",
          "title": "Memory Usage",
          "targets": [
            {
              "expr": "sum(container_memory_usage_bytes{image!=\"\"})",
              "legendFormat": "RAM"
            }
          ],
          "datasource": "Prometheus",
          "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 }
        },
        {
          "type": "graph",
          "title": "HTTP Requests per Second",
          "targets": [
            {
              "expr": "sum(rate(http_requests_total[1m]))",
              "legendFormat": "req/s"
            }
          ],
          "datasource": "Prometheus",
          "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 }
        },
        {
          "type": "graph",
          "title": "Network Bandwidth",
          "targets": [
            {
              "expr": "sum(rate(container_network_receive_bytes_total[5m]))",
              "legendFormat": "In"
            },
            {
              "expr": "sum(rate(container_network_transmit_bytes_total[5m]))",
              "legendFormat": "Out"
            }
          ],
          "datasource": "Prometheus",
          "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 }
        }
      ]
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: monitoring
  labels:
    app: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
