apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production

---

apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    pod-security.kubernetes.io/enforce: baseline