name: Run Tests
on:
  workflow_call:
jobs:
  compliance:
    name: Run Compliance Checker
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
    env:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_API_VERSION: 2024-02-15-preview

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build compliance binary
        working-directory: ./scripts
        run: |
          go build -o ../compliance-checker compliance-checker.go

      - name: Run compliance checker
        run: |
          chmod +x ./compliance-checker
          ./compliance-checker --dry-run \
            --azure-endpoint "$AZURE_OPENAI_ENDPOINT" \
            --azure-deployment "$AZURE_OPENAI_DEPLOYMENT" \
            --azure-api-key "$AZURE_OPENAI_API_KEY" \
            --api-version "$AZURE_OPENAI_API_VERSION" \
            --max-files 250 \
            --timeout 120 > compliance-report.txt

      - name: Upload compliance report
        uses: actions/upload-artifact@v4
        with:
          name: compliance-report
          path: compliance-report.txt