name: Multi-Cloud CI/CD Pipeline - Go Backend & JS Frontend

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  GO_VERSION: '1.21'
  NODE_VERSION: '20'
  TERRAFORM_VERSION: '1.5.7'
  KUBERNETES_VERSION: '1.33'
  CLOUD_PROVIDER: 'aws'  # azure | gcp | aws
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan (${{ matrix.cloud }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud: [aws]  # Ajouter azure, gcp selon besoins
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan \
            -var="cloud_provider=${{ matrix.cloud }}" \
            -out=tfplan-${{ matrix.cloud }}

      - name: Trivy Terraform Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: './terraform'
          format: 'sarif'
          output: 'trivy-terraform-${{ matrix.cloud }}.sarif'

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var="cloud_provider=${{ env.CLOUD_PROVIDER }}"

  build-backend:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    needs: [terraform-apply]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/backend:${{ github.sha }}
            ${{ secrets.REGISTRY_URL }}/backend:latest
          cache-from: type=registry,ref=${{ secrets.REGISTRY_URL }}/backend:buildcache
          cache-to: type=registry,ref=${{ secrets.REGISTRY_URL }}/backend:buildcache,mode=max

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.REGISTRY_URL }}/backend:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-image-backend.sarif'

  build-frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    needs: [terraform-apply]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/frontend:${{ github.sha }}
            ${{ secrets.REGISTRY_URL }}/frontend:latest

  kube:
    name: Initialize Kubernetes Cluster
    runs-on: ubuntu-latest
    needs: [terraform-apply, build-backend, build-frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }}\
            --name framework-ci-production-eks \
            --alias framework-ci

      - name: Apply manifests
        working-directory: ./k8s
        run: kubectl apply -f namespaces.yaml && kubectl apply -R -f .

      - name: Verify deployment
        run: kubectl get all

  check:
    name: Post deployment checks
    runs-on: ubuntu-latest
    needs: [kube]
    steps:
      - uses: actions/checkout@v4

      - name: Check App
        run: echo "TODO"

      - name: Check velero
        run: echo "TODO"

      - name: Check keycloak
        run: echo "TODO"

      - name: Check grafana
        run: echo "TODO"

      - name: Check prometheus
        run: echo "TODO"

      - name: Check vault
        run: echo "TODO"

  terraform-destroy:
    name: Terraform destroy
    runs-on: ubuntu-latest
    needs: [ check ]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve \
            -var="cloud_provider=${{ env.CLOUD_PROVIDER }}"